name: Release

on:
  create:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    # env:
    #   DOCKER_BUILDKIT: 0
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: "Fetch latest tag"
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Build and push Postgres 16
        id: docker_build_16
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PG_VERSION=16.3
            PG_MAJOR_VERSION=16
            VERSION=${{ steps.get-latest-tag.outputs.tag }}
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/streamersonglist/postgres-flex:16
            ghcr.io/streamersonglist/postgres-flex:16.3
            ghcr.io/streamersonglist/postgres-flex:${{ steps.get-latest-tag.outputs.tag }}

      - name: Postgres 16 Image digest
        run: echo ${{ steps.docker_build_16.outputs.digest }}
